# Author: Chuck Findlay <chuck@findlayis.me>
# License: LGPL v3.0

FROM gitea.findlayis.me/chuck/projectzomboid-docker:latest

RUN \
    apt-get update && \
    apt-get install --no-install-recommends -y cron=3.0pl1-162 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* 

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Install cloud SDK for GCS. This is large unfortunately
# TODO: Find a way to make this far smaller (we only really need gsutil to copy)
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg && apt-get update -y && apt-get install google-cloud-sdk -y
    

COPY gcp-start.sh /

CMD ["/gcp-start.sh"]